### PR TITLE
Modified api-config.yml to redirect logs

### PR DESCRIPTION
**Pull request by angelomendonca**
Modified the ansible config file to redirect the server requestlogs to {{monasca_log_dir}}/request.log. Also added the archival option.

### CODE REVIEW

**Comment by craigbr** [comment]
You added in two extra files. Please remove them.

Also switch the logging level back to WARN

**Comment by angelomendonca** [comment]
I deleted those 2 files and changed the level to warn. I also committed and pushed to the origin.

**Comment by tkuhlman** [comment]
Looks fine. A minor point is that you have 3 empty lines which seems a bit out of place.

**Comment by angelomendonca** [comment]
Deleted empty lines.

**Pull request merged**
